[features]
seeds = false
skip-lint = false
[programs.localnet]
chadlingo = "4hbWdGHR64ppsFyfqFNmR4FuUndAX9cHJvPqcqePWKpJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/nico/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
