[features]
seeds = false
skip-lint = false
[programs.localnet]
chadlingo = "5uuL3s2tWFk3paG9p4E4tRE1LxWjsWftfrYgUwYBh7jN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/nico/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
