[features]
seeds = false
skip-lint = false
[programs.localnet]
chadlingo = "4nNtVknm1ohyRyW7tSfHDZ3jFnbbFt2jc1az8fjUsmPp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/nico/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
